trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-Connection'
    regionName: 'us-east-1'
    stackName: 'test8294devops'
    templateSource: 'file'
    templateFile: 'Modules/Storage/S3/Template.yml'
    templateParametersFile: 'Modules/Storage/S3/Parameter.json'
    capabilityAutoExpand: true