resources:
  repositories:
    - repository: IaC-Automation
      type: git
      endpoint: IaC-Repo-Connection
      name: YASH-IaC-Centralized-AWS/IaC-Automation
      ref: refs/heads/main

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: IaC-Automation
- checkout: self

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS-Connection'
    regionName: 'us-east-1'
    stackName: 'test8294devops'
    templateSource: 'file'
    templateFile: 'IaC-Automation/Modules/Storage/S3/Template.yml'
    templateParametersFile: 'AWS-Infra/Modules/Storage/S3/Parameter.json'
    capabilityAutoExpand: true