resources:
  repositories:
    - repository: IaC-Automation
      type: git
      endpoint: IaC-Repo-Connection
      name: YASH-IaC-Centralized-AWS/IaC-Automation
      ref: refs/heads/main

variables:
- group: AWS-VG

- name: S3
  value: 'false'

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: IaC-Automation
- checkout: self

- task: CloudFormationCreateOrUpdateStack@1
  displayName: S3 Template
  condition: eq('${{ variables.S3}}', 'true')
  inputs:
    awsCredentials: '$(ServiceConnection)'
    regionName: 'us-east-1'
    stackName: '$(StackName)'
    templateSource: 'file'
    templateFile: 'IaC-Automation/Modules/Storage/S3/Template.yml'
    templateParametersFile: 'AWS-Infra/Modules/Storage/S3/Parameter.json'
    capabilityAutoExpand: true